### PR TITLE
Fix regression around ng-app not being on the body tag

### PR DESCRIPTION
**Pull request by alex-hall**
Added tests to make sure this regression never happens again.

### CODE REVIEW

**Comment by alex-hall** [comment]
Created a new PR since the last one was merged and the version bumped.

**Comment by alex-hall** [comment]
Not sure why travis CI is failing.. Everything is passing from my end.

**Comment by kbaum** [comment]
+1  This change seems to fix the issues on lastest 0.2.4 when ng-app is not on body tag.

**Comment by lalitkapoor** [comment]
+1

**Comment by wrozka** [comment]
Thanks!

**Comment by kbaum** [comment]
Thanks!

**Pull request merged**
